#!/bin/sh
# Pre-removal script for distiller-update

set -e

case "$1" in
remove | upgrade | deconfigure)
	# Clean up MOTD file if it exists
	[ -f /etc/update-motd.d/99-distiller-updates ] &&
		rm -f /etc/update-motd.d/99-distiller-updates
	;;

failed-upgrade) ;;

*)
	echo "prerm called with unknown argument '$1'" >&2
	exit 1
	;;
esac

#DEBHELPER#

exit 0
