# Distiller Update Configuration

# Check interval in seconds (minimum 3600 = 1 hour)
check_interval = 3600

# APT repository settings
repository_url = "http://apt.pamir.ai"
distribution = "testing"  # Options: stable, testing, unstable

# Notification settings
notify_motd = true   # Show updates in terminal MOTD
notify_dbus = true   # Send desktop notifications

# File paths
motd_file = "/etc/update-motd.d/99-distiller-updates"
cache_dir = "/var/cache/distiller-update"

# Logging
log_level = "info"  # Options: debug, info, warning, error

# APT command timeouts (in seconds)
apt_update_timeout = 120    # Timeout for apt-get update
apt_list_timeout = 60       # Timeout for apt list --upgradable
apt_query_timeout = 10      # Timeout for quick apt queries
apt_install_timeout = 1800  # Timeout for package installation

# APT update optimization (with isolated cache)
# When set, only updates the specified repository in an isolated APT cache directory.
# MUST be an absolute path (e.g., "/etc/apt/sources.list.d/pamir-ai.list")
# Comment out or set to None to update all repositories in system cache (default).
apt_source_file = "/etc/apt/sources.list.d/pamir-ai.list"

# Isolated APT cache directory (only used when apt_source_file is set)
# Prevents distiller-update from modifying system APT cache at /var/lib/apt/lists/
apt_cache_dir = "/var/cache/distiller-update/apt-cache"

# Policy settings
[policy]
restrict_prefixes = ["pamir-ai-", "distiller-", "claude-code-"]
allow_new_packages = true

# Bundle settings
[bundle.default]
packages = ["claude-code-web-manager", "distiller-sdk", "distiller-services", "distiller-cc", "distiller-update", "distiller-telemetry", "pamir-ai-eink-dkms", "pamir-ai-sam-dkms", "pamir-ai-soundcard-dkms"]
